### PR TITLE
45 auto enable jwt when re deploy edge functions

### LINKED ISSUE #45: Auto enable JWT when re-deploy edge functions
The edge functions always auto-enable the flag of `Enforce JWT Verification` after re-deployed.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pvinis** [comment]
Im trying to do the same, and its not really working. When you redeploy, does it keep the verification disabled?

**Comment by ghost** [comment]
> Im trying to do the same, and its not really working. When you redeploy, does it keep the verification disabled?

https://github.com/tuphan-dn/openblocks-wallet/blob/fd0e73af31b5436c5e2685b53662c4f5fe8e2bbd/supabase/config.toml#L197

Let’s say I have an api named ‘health’, then I must put a config as the file.

**Comment by pvinis** [comment]
Ah nevermind. I had to replace `health` with my own function's name. I thought it was a supabase thing, this `health`. Good luck with your project :)

**Comment by pvinis** [comment]
Lol same time. Thank you for the quick reply!

**Pull request merged**
